### should succeed

POST http://localhost:5200/api/login
Content-Type: application/json

{
  "name": "ballsies",
  "password": "abc123"
}

### should fail, incorrect password

POST http://localhost:5200/api/login
Content-Type: application/json

{
  "name": "ballsies",
  "password": "abc123."
}

### should fail, no such user

POST http://localhost:5200/api/login
Content-Type: application/json

{
  "name": "ballsies.",
  "password": "abc123"
}

### correct user name to test success

GET http://localhost:5200/api/login
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFsbHNpZXMiLCJpZCI6IjY0N2RiMzkyYjBhNzk1M2RlM2NmZDUxYyIsImlhdCI6MTY4NjMwMzI4OSwiZXhwIjoxNjg2MzA2ODg5fQ.f_I_mz1lMkFG5fKRYZNULgJj9y4oHANDzCkYO3jU4JI",
  "name": "ballsies"
}

### incorrect user name to test failure with valid token

GET http://localhost:5200/api/login
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmFsbHNpZXMiLCJpZCI6IjY0N2RiMzkyYjBhNzk1M2RlM2NmZDUxYyIsImlhdCI6MTY4NjMwMzI4OSwiZXhwIjoxNjg2MzA2ODg5fQ.f_I_mz1lMkFG5fKRYZNULgJj9y4oHANDzCkYO3jU4JI",
  "name": "allsbies"
}

###

