### post new ballsies, new password

POST http://localhost:5200/api/users
Content-Type: application/json

{
  "name": "ballsies",
  "password": "abc123"
}

### should fail (not a valid User object)

POST http://localhost:5200/api/users
Content-Type: application/json

{
  "nom": "ballsies"
}

###

DELETE http://localhost:5200/api/users
Content-Type: application/json

{
  "name": "ballsies"
}

###


